Feature repeatable text generation
databrickslabs/dbldatagen pull request #132
Opened 2022-10-23 21:54 UTC by ronanstokes-db

## Proposed changes
Draft PR for test coverage verification only

Describe the big picture of your changes here to communicate to the maintainers. 
If it fixes a bug or resolves a feature request, please provide a link to that issue.

## Types of changes

What types of changes does your code introduce to dbldatagen?
_Put an `x` in the boxes that apply_

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Change to tutorials, tests or examples
- [ ] Non code change (readme, images or other non-code assets)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. 
If you're unsure about any of them, don't hesitate to ask. We're here to help! 
This is simply a reminder of what we are going to look for before merging your code._

- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] Submission does not reduce code coverage numbers
- [ ] Submission does not increase alerts or messages from LGTM

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you 
did and what alternatives you considered, etc...

2023-01-14 01:13 UTC, howardwu-db commented
sample comment

2023-01-27 01:11 UTC, howardwu-db commented on dbldatagen/text_generators.py
> +    x          Insert a random lowercase hex digit
is there a reason why we use x for hex? I feel like it's more universal to represent with 'h' but I do know that "0x" is typical for hex

2023-01-27 01:13 UTC, howardwu-db commented on dbldatagen/text_generators.py
> +    x          Insert a random lowercase hex digit
ah nevermind I see that python itself uses x for hex https://docs.python.org/3/library/string.html#format-specification-mini-language

2023-01-30 14:47 UTC, howardwu-db requested changes
Have 3 questions

2023-01-31 23:52 UTC, ronanstokes-db commented on dbldatagen/text_generators.py
>          return random.randint(low, high)
performs better

2023-01-31 23:59 UTC, ronanstokes-db commented on dbldatagen/text_generators.py
> +            elif use_value and ('0' <= char <= '9'):
there is a different use in the if case so not every rule is the same

2023-02-01 00:13 UTC, ronanstokes-db commented on dbldatagen/text_generators.py
> +        masked_placeholders = np.ma.MaskedArray(placeholders, mask=False)
yes - intent is to start unmasked and mask rows as needed

2023-02-01 00:15 UTC, howardwu-db approved these changes

2023-02-01 00:16 UTC, merged