Feature generate from data revised
databrickslabs/dbldatagen pull request #204
Opened 2023-04-11 03:53 UTC by ronanstokes-db

## Proposed changes

Describe the big picture of your changes here to communicate to the maintainers. 
If it fixes a bug or resolves a feature request, please provide a link to that issue.

## Types of changes

What types of changes does your code introduce to dbldatagen?
_Put an `x` in the boxes that apply_

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Change to tutorials, tests or examples
- [ ] Non code change (readme, images or other non-code assets)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. 
If you're unsure about any of them, don't hesitate to ask. We're here to help! 
This is simply a reminder of what we are going to look for before merging your code._

- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] Submission does not reduce code coverage numbers
- [ ] Submission does not increase alerts or messages from prospector / lint

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you 
did and what alternatives you considered, etc...

2023-04-28 17:14 UTC, howardwu-db requested changes
need to get some more clarify on the categoricalvaluesthreshold comment

2023-04-28 17:14 UTC, howardwu-db commented on dbldatagen/data_analyzer.py
> +        :param categoricalValuesThreshold: Values will only be computed if less than threshold, If not supplied
what does computed values mean for categorical values?

2023-05-02 18:39 UTC, howardwu-db requested changes
need some minor editing changes

2026-07-30 18:03 UTC, josh-seidel-db commented
Thank you for this contribution. dbldatagen is moving to the new `dbldatagen.core` architecture (landed via #381), and we are not merging further changes into the legacy library. The capability here is either superseded by the new version or tracked as a fresh enhancement against the core engine. Closing as part of a repository cleanup; the branch and history remain available for reference.

2026-07-30 18:03 UTC, closed without merging