Changes and bug fixes to support shared clusters in DBR 14.2
databrickslabs/dbldatagen pull request #248
Opened 2023-12-18 08:46 UTC by ronanstokes-db

## Proposed changes

When using a shared cluster with UC shared mode in DBR 14.2, referencing the sparkContext produces an attribute error. 
To fix this, if an error is thrown when accessing the sparkContext, we use a default parallelism of 200 unless an alternative
value was explicitly specified. 

This PR also uses the Spark SQL function element_at rather than direct array indexing due to incompatibilities with some spark versions. 

## Types of changes

What types of changes does your code introduce to dbldatagen?
_Put an `x` in the boxes that apply_

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Change to tutorials, tests or examples
- [ ] Non code change (readme, images or other non-code assets)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. 
If you're unsure about any of them, don't hesitate to ask. We're here to help! 
This is simply a reminder of what we are going to look for before merging your code._

- [x] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] Submission does not reduce code coverage numbers
- [x] Submission does not increase alerts or messages from prospector / lint

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you 
did and what alternatives you considered, etc...

2023-12-20 16:08 UTC, howardwu-db reviewed
Make some grammar fixes here.

I'm a bit curious what db's stance is on porting code to shared clusters. It seems like they should try to have backward compatibility built in for the missing spark context?

2023-12-20 16:08 UTC, howardwu-db commented on CHANGELOG.md
> +* Updated code to use Sparks SQL function `element_at` instead of array indexing due to incompatibility
"Spark's"

2023-12-20 16:08 UTC, howardwu-db commented on tests/test_shared_env.py
> +    attribute to get the default parallelism. In this cases, we want to catch errors and return a default of
In this case not cases

2023-12-28 02:53 UTC, howardwu-db requested changes
See requested changes as noted

2024-01-16 23:27 UTC, howardwu-db reviewed
look good

2024-01-16 23:28 UTC, howardwu-db approved these changes
looks good

2024-02-19 14:51 UTC, GeekSheikh commented
It's working for me. We're testing it a little deeper but looks good. Please don't forget to bump the version.

2024-02-19 14:51 UTC, GeekSheikh approved these changes
please don't forget to bump the version but looks to be working on 14.3 LTS.

2024-02-22 22:07 UTC, merged