Feature constraints
databrickslabs/dbldatagen pull request #257
Opened 2024-03-13 22:27 UTC by ronanstokes-db

## Proposed changes

Added support for constraints

## Types of changes

What types of changes does your code introduce to dbldatagen?
_Put an `x` in the boxes that apply_

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Change to tutorials, tests or examples
- [x] Non code change (readme, images or other non-code assets)
- [x] Documentation Update (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. 
If you're unsure about any of them, don't hesitate to ask. We're here to help! 
This is simply a reminder of what we are going to look for before merging your code._

- [x] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] Submission does not reduce code coverage numbers
- [x] Submission does not increase alerts or messages from prospector / lint

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you 
did and what alternatives you considered, etc...

2024-04-19 18:36 UTC, howardwu-db requested changes
Probably add comments to the abstract classes instead of using ABC

2024-04-19 23:05 UTC, ronanstokes-db commented on dbldatagen/column_spec_options.py
> +    :param baseColumnType: Determines how the value is derived from the base column. Possible values are 'auto',
Fixed in coming checkin

2024-05-23 22:50 UTC, ronanstokes-db commented on dbldatagen/column_spec_options.py
> +    :param baseColumnType: Determines how the value is derived from the base column. Possible values are 'auto',
moved to different PR

2024-05-24 09:21 UTC, ronanstokes-db commented on dbldatagen/constraints/constraint.py
> +    @classmethod
The class has been reworked so no longer applicable (i think)

2024-05-25 14:33 UTC, howardwu-db approved these changes

2024-05-28 20:11 UTC, merged